### ISSUE TITLE
you stole my idea

### ISSUE THREAD

**Issue by JoelSalzesson** [shreyash0k/PotholeDetection#1]
you stole my idea, you owe me

**Comment by shreyash0k** [comment]
First of all I got this idea by experiencing roads in my hometown. 
Second I referred these papers to get more info 
https://ieeexplore.ieee.org/document/8692120
https://ieeexplore.ieee.org/document/5982206

I did not understand, in what reference you said "you stole my idea"

**Comment by shreyash0k** [comment]
> you stole my idea, you owe me
First of all I got this idea by experiencing roads in my hometown. 
Second I referred these papers to get more info about possible solutions
https://ieeexplore.ieee.org/document/8692120
https://ieeexplore.ieee.org/document/5982206
I did not understand, in what reference you are saying  "you stole my idea"
